(cl:defpackage ogretici_paket-msg
  (:use )
  (:export
   "<BATARYADURUM>"
   "BATARYADURUM"
   "<GOREVDURUMACTION>"
   "GOREVDURUMACTION"
   "<GOREVDURUMACTIONFEEDBACK>"
   "GOREVDURUMACTIONFEEDBACK"
   "<GOREVDURUMACTIONGOAL>"
   "GOREVDURUMACTIONGOAL"
   "<GOREVDURUMACTIONRESULT>"
   "GOREVDURUMACTIONRESULT"
   "<GOREVDURUMFEEDBACK>"
   "GOREVDURUMFEEDBACK"
   "<GOREVDURUMGOAL>"
   "GOREVDURUMGOAL"
   "<GOREVDURUMRESULT>"
   "GOREVDURUMRESULT"
  ))

