; Auto-generated. Do not edit!


(cl:in-package ogretici_paket-msg)


;//! \htmlinclude GorevDurumResult.msg.html

(cl:defclass <GorevDurumResult> (roslisp-msg-protocol:ros-message)
  ((sonuc
    :reader sonuc
    :initarg :sonuc
    :type cl:string
    :initform ""))
)

(cl:defclass GorevDurumResult (<GorevDurumResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GorevDurumResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GorevDurumResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ogretici_paket-msg:<GorevDurumResult> is deprecated: use ogretici_paket-msg:GorevDurumResult instead.")))

(cl:ensure-generic-function 'sonuc-val :lambda-list '(m))
(cl:defmethod sonuc-val ((m <GorevDurumResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ogretici_paket-msg:sonuc-val is deprecated.  Use ogretici_paket-msg:sonuc instead.")
  (sonuc m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GorevDurumResult>) ostream)
  "Serializes a message object of type '<GorevDurumResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'sonuc))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'sonuc))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GorevDurumResult>) istream)
  "Deserializes a message object of type '<GorevDurumResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'sonuc) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'sonuc) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GorevDurumResult>)))
  "Returns string type for a message object of type '<GorevDurumResult>"
  "ogretici_paket/GorevDurumResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GorevDurumResult)))
  "Returns string type for a message object of type 'GorevDurumResult"
  "ogretici_paket/GorevDurumResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GorevDurumResult>)))
  "Returns md5sum for a message object of type '<GorevDurumResult>"
  "4b7dca703b626d43925cc803ca5a123c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GorevDurumResult)))
  "Returns md5sum for a message object of type 'GorevDurumResult"
  "4b7dca703b626d43925cc803ca5a123c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GorevDurumResult>)))
  "Returns full string definition for message of type '<GorevDurumResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string sonuc~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GorevDurumResult)))
  "Returns full string definition for message of type 'GorevDurumResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string sonuc~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GorevDurumResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'sonuc))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GorevDurumResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GorevDurumResult
    (cl:cons ':sonuc (sonuc msg))
))
