; Auto-generated. Do not edit!


(cl:in-package ogretici_paket-msg)


;//! \htmlinclude GorevDurumGoal.msg.html

(cl:defclass <GorevDurumGoal> (roslisp-msg-protocol:ros-message)
  ((birim
    :reader birim
    :initarg :birim
    :type cl:integer
    :initform 0))
)

(cl:defclass GorevDurumGoal (<GorevDurumGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GorevDurumGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GorevDurumGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ogretici_paket-msg:<GorevDurumGoal> is deprecated: use ogretici_paket-msg:GorevDurumGoal instead.")))

(cl:ensure-generic-function 'birim-val :lambda-list '(m))
(cl:defmethod birim-val ((m <GorevDurumGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ogretici_paket-msg:birim-val is deprecated.  Use ogretici_paket-msg:birim instead.")
  (birim m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GorevDurumGoal>) ostream)
  "Serializes a message object of type '<GorevDurumGoal>"
  (cl:let* ((signed (cl:slot-value msg 'birim)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GorevDurumGoal>) istream)
  "Deserializes a message object of type '<GorevDurumGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'birim) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GorevDurumGoal>)))
  "Returns string type for a message object of type '<GorevDurumGoal>"
  "ogretici_paket/GorevDurumGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GorevDurumGoal)))
  "Returns string type for a message object of type 'GorevDurumGoal"
  "ogretici_paket/GorevDurumGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GorevDurumGoal>)))
  "Returns md5sum for a message object of type '<GorevDurumGoal>"
  "4e056b4faf5ea83c15f76d58046e4e31")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GorevDurumGoal)))
  "Returns md5sum for a message object of type 'GorevDurumGoal"
  "4e056b4faf5ea83c15f76d58046e4e31")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GorevDurumGoal>)))
  "Returns full string definition for message of type '<GorevDurumGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 birim~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GorevDurumGoal)))
  "Returns full string definition for message of type 'GorevDurumGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 birim~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GorevDurumGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GorevDurumGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GorevDurumGoal
    (cl:cons ':birim (birim msg))
))
