// Auto-generated. Do not edit!

// (in-package ogretici_paket.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GorevDurumResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.sonuc = null;
    }
    else {
      if (initObj.hasOwnProperty('sonuc')) {
        this.sonuc = initObj.sonuc
      }
      else {
        this.sonuc = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GorevDurumResult
    // Serialize message field [sonuc]
    bufferOffset = _serializer.string(obj.sonuc, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GorevDurumResult
    let len;
    let data = new GorevDurumResult(null);
    // Deserialize message field [sonuc]
    data.sonuc = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.sonuc);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ogretici_paket/GorevDurumResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4b7dca703b626d43925cc803ca5a123c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string sonuc
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GorevDurumResult(null);
    if (msg.sonuc !== undefined) {
      resolved.sonuc = msg.sonuc;
    }
    else {
      resolved.sonuc = ''
    }

    return resolved;
    }
};

module.exports = GorevDurumResult;
