// Auto-generated. Do not edit!

// (in-package ogretici_paket.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GorevDurumGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.birim = null;
    }
    else {
      if (initObj.hasOwnProperty('birim')) {
        this.birim = initObj.birim
      }
      else {
        this.birim = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GorevDurumGoal
    // Serialize message field [birim]
    bufferOffset = _serializer.int32(obj.birim, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GorevDurumGoal
    let len;
    let data = new GorevDurumGoal(null);
    // Deserialize message field [birim]
    data.birim = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ogretici_paket/GorevDurumGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4e056b4faf5ea83c15f76d58046e4e31';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 birim
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GorevDurumGoal(null);
    if (msg.birim !== undefined) {
      resolved.birim = msg.birim;
    }
    else {
      resolved.birim = 0
    }

    return resolved;
    }
};

module.exports = GorevDurumGoal;
