// Generated by gencpp from file ogretici_paket/GecenZaman.msg
// DO NOT EDIT!


#ifndef OGRETICI_PAKET_MESSAGE_GECENZAMAN_H
#define OGRETICI_PAKET_MESSAGE_GECENZAMAN_H

#include <ros/service_traits.h>


#include <ogretici_paket/GecenZamanRequest.h>
#include <ogretici_paket/GecenZamanResponse.h>


namespace ogretici_paket
{

struct GecenZaman
{

typedef GecenZamanRequest Request;
typedef GecenZamanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GecenZaman
} // namespace ogretici_paket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ogretici_paket::GecenZaman > {
  static const char* value()
  {
    return "d89a3e566b5de459800ae97d9237aa5b";
  }

  static const char* value(const ::ogretici_paket::GecenZaman&) { return value(); }
};

template<>
struct DataType< ::ogretici_paket::GecenZaman > {
  static const char* value()
  {
    return "ogretici_paket/GecenZaman";
  }

  static const char* value(const ::ogretici_paket::GecenZaman&) { return value(); }
};


// service_traits::MD5Sum< ::ogretici_paket::GecenZamanRequest> should match
// service_traits::MD5Sum< ::ogretici_paket::GecenZaman >
template<>
struct MD5Sum< ::ogretici_paket::GecenZamanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ogretici_paket::GecenZaman >::value();
  }
  static const char* value(const ::ogretici_paket::GecenZamanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ogretici_paket::GecenZamanRequest> should match
// service_traits::DataType< ::ogretici_paket::GecenZaman >
template<>
struct DataType< ::ogretici_paket::GecenZamanRequest>
{
  static const char* value()
  {
    return DataType< ::ogretici_paket::GecenZaman >::value();
  }
  static const char* value(const ::ogretici_paket::GecenZamanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ogretici_paket::GecenZamanResponse> should match
// service_traits::MD5Sum< ::ogretici_paket::GecenZaman >
template<>
struct MD5Sum< ::ogretici_paket::GecenZamanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ogretici_paket::GecenZaman >::value();
  }
  static const char* value(const ::ogretici_paket::GecenZamanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ogretici_paket::GecenZamanResponse> should match
// service_traits::DataType< ::ogretici_paket::GecenZaman >
template<>
struct DataType< ::ogretici_paket::GecenZamanResponse>
{
  static const char* value()
  {
    return DataType< ::ogretici_paket::GecenZaman >::value();
  }
  static const char* value(const ::ogretici_paket::GecenZamanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OGRETICI_PAKET_MESSAGE_GECENZAMAN_H
