// Generated by gencpp from file basit_uygulamalar/CemberHareket.msg
// DO NOT EDIT!


#ifndef BASIT_UYGULAMALAR_MESSAGE_CEMBERHAREKET_H
#define BASIT_UYGULAMALAR_MESSAGE_CEMBERHAREKET_H

#include <ros/service_traits.h>


#include <basit_uygulamalar/CemberHareketRequest.h>
#include <basit_uygulamalar/CemberHareketResponse.h>


namespace basit_uygulamalar
{

struct CemberHareket
{

typedef CemberHareketRequest Request;
typedef CemberHareketResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CemberHareket
} // namespace basit_uygulamalar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basit_uygulamalar::CemberHareket > {
  static const char* value()
  {
    return "534fdc954659adaf837ecd56d547676d";
  }

  static const char* value(const ::basit_uygulamalar::CemberHareket&) { return value(); }
};

template<>
struct DataType< ::basit_uygulamalar::CemberHareket > {
  static const char* value()
  {
    return "basit_uygulamalar/CemberHareket";
  }

  static const char* value(const ::basit_uygulamalar::CemberHareket&) { return value(); }
};


// service_traits::MD5Sum< ::basit_uygulamalar::CemberHareketRequest> should match
// service_traits::MD5Sum< ::basit_uygulamalar::CemberHareket >
template<>
struct MD5Sum< ::basit_uygulamalar::CemberHareketRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basit_uygulamalar::CemberHareket >::value();
  }
  static const char* value(const ::basit_uygulamalar::CemberHareketRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basit_uygulamalar::CemberHareketRequest> should match
// service_traits::DataType< ::basit_uygulamalar::CemberHareket >
template<>
struct DataType< ::basit_uygulamalar::CemberHareketRequest>
{
  static const char* value()
  {
    return DataType< ::basit_uygulamalar::CemberHareket >::value();
  }
  static const char* value(const ::basit_uygulamalar::CemberHareketRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basit_uygulamalar::CemberHareketResponse> should match
// service_traits::MD5Sum< ::basit_uygulamalar::CemberHareket >
template<>
struct MD5Sum< ::basit_uygulamalar::CemberHareketResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basit_uygulamalar::CemberHareket >::value();
  }
  static const char* value(const ::basit_uygulamalar::CemberHareketResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basit_uygulamalar::CemberHareketResponse> should match
// service_traits::DataType< ::basit_uygulamalar::CemberHareket >
template<>
struct DataType< ::basit_uygulamalar::CemberHareketResponse>
{
  static const char* value()
  {
    return DataType< ::basit_uygulamalar::CemberHareket >::value();
  }
  static const char* value(const ::basit_uygulamalar::CemberHareketResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASIT_UYGULAMALAR_MESSAGE_CEMBERHAREKET_H
